---
- name: Printing variables
  hosts: cisco
  gather_facts: false
  connection: local

  tasks:
    - name:sh ver
  ansible.netcommon.cli_command:
        command: "{{ show ip int brie }}"
         
