---
- name: Printing variables
  hosts: cisco
  gather_facts: false
  connection: local

  tasks:


#  - name: Add loopback
    
#    cisco.ios.ios_interface:
#      name: Loopback1
 #     state: present      

  - name: display hostname

    debug: 
      msg: "THE HOST NAME IS {{ ansible_net_hostname }}"
    
      debug:
       msg: "{{ ansible_net_version }}"

