---
- name: Printing variables
  hosts: routers

  tasks:

    - name: list IPs
      debug:
        msg: "{{ ansible_net_all_ipv4_addresses }}" #This pulls all the IP Addresses
    
    - name: create Loopback # WORKING for creating interfaces
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback1
            description: TEST-Loopback
            enabled: true

     

    - name: display hostname

      debug: 
       msg: "THE HOST NAME IS {{ ansible_net_hostname }}" 
       # WORKING display variable with custom note
    
      #  debug:
      #    msg: "{{ ios_interface }}"

