---
- name: Printing variables
  hosts: cisco
  gather_facts: True
  connection: local
  ansible_user: "omkar"
  ansible_pass: "omkar"

  tasks:


#  - name: Add loopback
 #   gather_subset: all
    
#    cisco.ios.ios_interface:
#      name: Loopback1
 #     state: present      

  - name: display hostname

    debug: 
      msg: "THE HOST NAME IS {{ ansible_net_hostname }}"
    
      debug:
        msg: "{{ ansible_net_version }}"

