---
- name: Printing variables
  hosts: routers

  tasks:

    - name: list IPs
      debug:
        msg: {{ ansible_net_all_ipv4_addresses }}
    
    - name: create Loopback
      cisco.ios.ios_interfaces:
        config:
          - name: Loopback1
            description: TEST-Loopback
            enabled: true

#    cisco.ios.ios_interface:
#      name: Loopback1
 #     state: present      

    # - name: display hostname

    #   debug: 
    #    msg: "THE HOST NAME IS {{ ansible_net_hostname }}"
    
    #    debug:
    #      msg: "{{ ios_interface }}"

