---
- name: cisco transfer
  hosts: cisco
  gather_facts: false
  connection: local

  tasks:
    - name: testing
      cisco_file_transfer:
        source_file="/home/omkar/om/test"
        dest_file=test
        enable_scp=True
        host={{ ansible_host }}
        username={{ ansible_user }}
        password={{ ansible_pass }}
